name: Compile

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  arduino:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v2
      - name: Compile sketch
        run: ./scripts/compile.sh
